#!/usr/bin/env ruby

file = File.symlink?(__FILE__) ? File.readlink(__FILE__) : __FILE__
file = File.expand_path(File.dirname(file))
$LOAD_PATH.unshift File.expand_path('../lib', file)

require 'naifa'
require 'naifa/cli'
Naifa::CLI.start
